<h2>Oi, {first_name}!</h2>
<p>
    Obrigado por participar do {event_name}!
    Aqui está seu certificado.
</p>

<p>
    Qualquer problema, basta entrar em
    <a href="{event_site}">contato</a>.
</p>

<div class="items">
    <div class="item">
        <a href="{img_link}"><img src="{img_link}" width="250" /></a>
    </div>
</div>

<p>
    <small>Para salvar, clique com o botão direito e escolha "salvar como". Impressão em A4 90DPI.</small>
</p>