version: '2'
services:
  webserver:
    build: .
    ports:
     - '80:80'
    volumes:
     - .:/var/www/html
    links:
     - database
  database:
    image: mysql:5.7
    ports:
     - '3306:3306'
    environment:
     - MYSQL_ROOT_PASSWORD=confphprs
     - MYSQL_PASSWORD=confphprs
     - MYSQL_DATABASE=confphprs
     - MYSQL_USER=confphprs
    volumes:
     - mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}
